workflows:
    issue_status_workflow:
        label: 'oro.issue.flow.label'
        entity: Slava\Bundle\IssueBundle\Entity\Issue
        entity_attribute: issue
        start_step: open
        steps_display_ordered: true

        steps:
            open:
                label: 'oro.issue.flow.open'
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                label: 'oro.issue.flow.open.in_progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            closed:
                label: 'in_progress.closed'
                order: 30
                allowed_transitions:
                    - reopen
            resolved:
                label: 'in_progress.resolved'
                order: 40
                allowed_transitions:
                    - close
                    - reopen

        attributes:
            resolution:
                label: 'oro.issue.resilution.label'
                property_path: issue.resolution
                type: string

        transitions:
            open_issue:
                label: 'oro.issue.flow.open_issue'
                step_to: open
                is_start: true
                transition_definition: open_definition
            start_progress:
                label: 'oro.issue.flow.start_progress'
                step_to: in_progress
                frontend_options:
                    class: 'btn-primary'
                    icon: 'icon-play'
                transition_definition: start_progress_definition
            stop_progress:
                label: 'oro.issue.flow.stop_progress'
                step_to: open
                frontend_options:
                    class: 'btn-primary'
                    icon: 'icon-stop'
                transition_definition: stop_progress_definition
            resolve:
                label: 'oro.issue.flow.resolve'
                step_to: resolved
                frontend_options:
                    icon: 'icon-star'
                transition_definition: resolved_definition
            close:
                label: 'oro.issue.flow.close'
                step_to: closed
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
            reopen:
                label: 'oro.issue.flow.reopen'
                step_to: open
                frontend_options:
                    icon: 'icon-refresh'
                transition_definition: reopen_definition

        transition_definitions:
            open_definition:
                post_actions:
                    - @assign_value:
                        - [$resolution, 3]
            start_progress_definition:
                post_actions:
                    - @assign_value:
                        - [$resolution, 3]
            stop_progress_definition:
                post_actions:
                    - @assign_value:
                        - [$resolution, 3]
            reopen_definition:
                post_actions:
                    - @assign_value:
                        - [$resolution, 3]
            resolved_definition: ~
            closed_definition: ~
